In [3]:
from sklearn import preprocessing #preprocesamiento de datos
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/polla/Desktop/curso python esecencial ciencia de datos/machine learning/datos1.csv",nrows=1000)
df= df[["Price","Bathrooms","Bedrooms","ParkingSlots","SquareMeters"]].dropna()

In [2]:
df.head()

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México

In [4]:
#escalar los datos el mas popular es el estandarizado 
X_scaled=preprocessing.scale(df)
X_scaled

C:\Users\polla\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.

array([[ 0.47009432,  1.5383543 ,  1.69151999,  2.19798237,  1.8343123 ],
       [-1.02909721, -0.73395634, -1.16336607, -1.37017083, -0.97001133],
       [-0.26226927,  0.40219898,  0.26407696, -0.18078643, -0.22500304],
       ...,
       [ 0.81473602, -0.73395634,  0.26407696, -1.37017083,  0.0772173 ],
       [-0.58537086, -0.73395634,  0.26407696, -0.18078643, -0.36557064],
       [-0.59829492,  0.40219898,  0.26407696, -0.18078643, -0.31306865]])

In [5]:
X_scaled.mean(axis=0) #media para cada 1 de las columnas  sin llegar a ser 0 es 0

array([ 0.00000000e+00,  7.81597009e-17,  1.13686838e-16, -1.42108547e-16,
        3.55271368e-17])

In [6]:
X_scaled.std(axis=0) # lo mismo para la desviacion etsandar 
#convirtio nuevas  variables  a nuevas escalas escala que esta centrada en 0  tiene una desviacion estadnar igual a1

array([1., 1., 1., 1., 1.])

In [7]:
df.iloc[2] #podemos  ver los detalles del  fila 2 escalonado

Price           5250000.0
Bathrooms             3.0
Bedrooms              3.0
ParkingSlots          2.0
SquareMeters        177.0
Name: 2, dtype: float64

In [8]:
X_scaled[2] #esta por debajo de la media

array([-0.26226927,  0.40219898,  0.26407696, -0.18078643, -0.22500304])

In [13]:
min_max_scaler = preprocessing.MinMaxScaler([0,10]) # escala de minimo maximo rango de valores que tenga  clasica de 10 
X_train_minmax=min_max_scaler.fit_transform(df)# lo va adaptar ala df y se hace con fit transform  
X_train_minmax

C:\Users\polla\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

array([[ 2.59729272, 10.        , 10.        , 10.        ,  3.15480558],
       [ 0.14382375,  3.33333333,  3.33333333,  0.        ,  0.22743947],
       [ 1.39875917,  6.66666667,  6.66666667,  3.33333333,  1.00513573],
       ...,
       [ 3.16130852,  3.33333333,  6.66666667,  0.        ,  1.32061629],
       [ 0.86999436,  3.33333333,  6.66666667,  3.33333333,  0.85840059],
       [ 0.84884377,  6.66666667,  6.66666667,  3.33333333,  0.91320616]])

In [15]:
#VARIABLES CATEGORICAS ES DECIR AQUELLAS QUE NO SON NUMERICAS EN UNA VARIABLE DAMI
df=pd.read_csv("C:/Users/polla/Desktop/curso python esecencial ciencia de datos/machine learning/datos1.csv",nrows=100)
pd.get_dummies (df["Municipio"])
#0 no sea esa casa o 1  consume mucha memoria  en una columna  ahora tenemos una columna par acada 1 de la s categoria

,Acapulco,Actopan,Atizapán de Zaragoza,Benito Juarez,Benito Juárez,Coacalco de Berriozábal,Coyoacán,Cuajimalpa,Cuauhtémoc,Cuautitlán Izcalli Municipality,...,Santiago de Querétaro,Tenancingo Municipality,Tequisquiapan Municipality,Tizayuca,Tlalpan,Venustiano Carranza,Xochimilco,Xochitepec,Zempoala,Álvaro Obregón
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0