In [3]:
import pandas as pd

df=pd.read_csv("C:/Users/polla/Desktop/curso python esecencial ciencia de datos/evaluar eficeincia del codigo/datos1.csv",nrows=1e6)
#nrows=1e6 10 elevado ala 6  hace 1 millon de datos

In [4]:
dfduplicate=df.append(df) # mismo df por duplicadado

In [7]:
dfduplicate=dfduplicate.sample(frac=1) #reordenamiento

In [10]:
dfduplicate.head(10)

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
6532,730000.0,2,3,2,86.0,-100.395297,20.982897,San José Iturbide,Guanajuato
10437,2450000.0,3,3,2,480.0,-89.521437,21.072211,Conkal Municipality,Yucatán
8842,1795000.0,2,2,2,82.0,-89.623835,21.026241,Merida,Yucatán
7146,990000.0,3,3,1,85.0,-96.123917,19.126730,Boca del Río,Veracruz
5033,3141600.0,2,2,1,64.0,-99.156100,19.392928,NaN,Ciudad de México
785,2300000.0,3,3,2,130.0,-100.347966,20.595192,Santiago de Querétaro,Querétaro
8118,3250000.0,2,4,4,625.0,-110.308514,24.162234,La Paz,Baja California Sur
2447,3350000.0,4,3,3,513.0,-98.422535,18.882489,Atlixco Municipality,Puebla
11724,1450000.0,2,3,2,160.0,-106.154513,28.712708,Chihuahua,Chihuahua
12499,1479602.0,3,3,2,214.0,-98.801392,20.012828,Zempoala,Hidalgo

In [11]:
dfclean=dfduplicate.drop_duplicates () # ya eliminamos los datos duplicados

In [12]:
len(dfclean)==len(df) #quiere decir que no es lo mismo la df   de los mismos datos   si no se han quitado datos duplicados

False

In [17]:
len(df)#dataframe inicial filas

16459

In [16]:
len(dfduplicate)#base de datos artificial creada para limpiar datos

32918

In [15]:
len(dfclean)#df limpia sin datos  repetidos

15517

In [18]:
dfclean.drop_duplicates(subset= "Municipio")#se puede ver las columnas repetidas

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
6532,730000.0,2,3,2,86.0,-100.395297,20.982897,San José Iturbide,Guanajuato
10437,2450000.0,3,3,2,480.0,-89.521437,21.072211,Conkal Municipality,Yucatán
8842,1795000.0,2,2,2,82.0,-89.623835,21.026241,Merida,Yucatán
7146,990000.0,3,3,1,85.0,-96.123917,19.126730,Boca del Río,Veracruz
5033,3141600.0,2,2,1,64.0,-99.156100,19.392928,NaN,Ciudad de México
...,...,...,...,...,...,...,...,...,...
11884,550000.0,1,1,1,90.0,-96.792221,17.184421,Guadalupe Etla,Oaxaca
14359,1325000.0,3,3,1,89.0,-98.899550,19.561025,Chiconcuac de Juárez,Estado de México
1537,2900000.0,4,4,4,397.0,-101.918814,20.928110,Purísima del Rincón,Guanajuato
9817,1100000.0,1,3,1,400.0,-99.095278,20.166456,Ajacuba,Hidalgo
14886,490000.0,1,2,2,97.0,-99.809454,20.225426,Polotitlán,Estado de México

In [19]:
df.dropna()
#si no muestra nada entonces nuestra base de datos no tienen Nan y si aparece es por que tenemos datos faltantes

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000.0,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999.0,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000.0,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000.0,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000.0,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México
...,...,...,...,...,...,...,...,...,...
16099,4240000.0,4,4,3,379.0,-110.978419,29.079118,Hermosillo,Sonora
16100,4000000.0,3,3,3,312.0,-109.984521,27.502475,Cajeme,Sonora
16101,1250000.0,2,2,2,140.0,-110.304312,24.183406,La Paz,Baja California Sur
16102,2950000.0,4,3,2,230.0,-111.006419,29.078518,Hermosillo,Sonora
16103,830000.0,2,3,1,171.0,-111.010119,29.106787,Hermosillo,Sonora

In [22]:
df.dropna(thresh=1 )#llena de informacion de datos relevantes relevante columna

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000.0,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999.0,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000.0,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000.0,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000.0,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México
...,...,...,...,...,...,...,...,...,...
16454,5300000.0,3,3,2,428.0,-106.456574,23.279159,NaN,Sinaloa
16455,3400000.0,4,4,2,2000.0,-101.711308,21.152332,NaN,Guanajuato
16456,1848000.0,3,3,2,128.0,-102.330020,21.883083,NaN,Aguascalientes
16457,1900000.0,3,3,2,125.0,-101.619522,21.099614,NaN,Guanajuato
16458,3200000.0,4,4,3,360.0,-101.631316,21.115931,NaN,Guanajuato

In [23]:
df.dropna(thresh=9 ) #en este caso son las 9 columnas

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000.0,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999.0,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000.0,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000.0,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000.0,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México
...,...,...,...,...,...,...,...,...,...
16099,4240000.0,4,4,3,379.0,-110.978419,29.079118,Hermosillo,Sonora
16100,4000000.0,3,3,3,312.0,-109.984521,27.502475,Cajeme,Sonora
16101,1250000.0,2,2,2,140.0,-110.304312,24.183406,La Paz,Baja California Sur
16102,2950000.0,4,3,2,230.0,-111.006419,29.078518,Hermosillo,Sonora
16103,830000.0,2,3,1,171.0,-111.010119,29.106787,Hermosillo,Sonora

In [25]:
df.dropna(thresh=len(df.columns)-2 )#una manera de usar bien el codigo
#el codigo dice que como maximo tengamos  -1  dato dfaltante

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000.0,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999.0,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000.0,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000.0,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000.0,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México
...,...,...,...,...,...,...,...,...,...
16454,5300000.0,3,3,2,428.0,-106.456574,23.279159,NaN,Sinaloa
16455,3400000.0,4,4,2,2000.0,-101.711308,21.152332,NaN,Guanajuato
16456,1848000.0,3,3,2,128.0,-102.330020,21.883083,NaN,Aguascalientes
16457,1900000.0,3,3,2,125.0,-101.619522,21.099614,NaN,Guanajuato
16458,3200000.0,4,4,3,360.0,-101.631316,21.115931,NaN,Guanajuato

In [26]:
df.dropna (subset=["Municipio"]) # nos duevuelve un data frame sin Nan en esa columna

,Price,Bathrooms,Bedrooms,ParkingSlots,SquareMeters,GpsLongitude,GpsLatitude,Municipio,Estado
0,9500000.0,4,4,4,470.0,-89.611038,21.063482,Merida,Yucatán
1,799999.0,2,2,1,71.0,-100.398136,20.663553,Santiago de Querétaro,Querétaro
2,5250000.0,3,3,2,177.0,-99.299350,19.355751,Cuajimalpa,Ciudad de México
3,8200000.0,2,3,3,156.0,-99.164989,19.393514,Benito Juarez,Ciudad de México
4,6250000.0,3,3,3,200.0,-99.293693,19.356364,Cuajimalpa,Ciudad de México
...,...,...,...,...,...,...,...,...,...
16099,4240000.0,4,4,3,379.0,-110.978419,29.079118,Hermosillo,Sonora
16100,4000000.0,3,3,3,312.0,-109.984521,27.502475,Cajeme,Sonora
16101,1250000.0,2,2,2,140.0,-110.304312,24.183406,La Paz,Baja California Sur
16102,2950000.0,4,3,2,230.0,-111.006419,29.078518,Hermosillo,Sonora
16103,830000.0,2,3,1,171.0,-111.010119,29.106787,Hermosillo,Sonora